---
name: build
run-name: Build
on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  build:
    name: Build Firmware
    runs-on: Ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: HIDRelayController attiny261
            cross:
              - cross/HIDRelayController_cross.txt
              - cross/attiny261_cross.txt
            options: "-Dusb_serial_id=false"

          - name: HIDRelayController attiny461
            cross:
              - cross/HIDRelayController_cross.txt
              - cross/attiny461_cross.txt
            options: ""

          - name: HIDRelayController attiny861
            cross:
              - cross/HIDRelayController_cross.txt
              - cross/attiny861_cross.txt
            options: ""

          - name: dcttech 8 channel
            cross:
              - cross/dcttech_8ch_cross.txt
            options: ""

          - name: dcttech 2 channel
            cross:
              - cross/dcttech_2ch_cross.txt
            options: ""

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update apt
        run: sudo apt update -y

      - name: Install Dependencies
        run: |
          sudo apt install -y gcc-avr binutils-avr avr-libc avrdude meson clang-format

      - name: Configure ${{ matrix.name }}
        run: |
          meson setup --cross-file=${{ join( matrix.cross, ' --cross-file=') }} ${{ matrix.options }} builddir

      - name: Check formatting
        run: |
          ninja -C builddir clang-format-check

      - name: Build ${{ matrix.name }}
        run: |
          ninja -C builddir

      - name: Create hex files for ${{ matrix.name }}
        run: |
          ninja -C builddir hidrelay.hex hidrelay.ee.hex

      - name: Create fuse config for ${{ matrix.name }}
        run: |
          ninja -C builddir fuses.txt

      - name: Show stats for ${{ matrix.name }}
        run: |
          ninja -C builddir stats

      - name: Upload flash file
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: builddir/hidrelay.hex
          asset_name: "${{ matrix.name }} flash.hex"
        if: "github.event_name == 'push' && github.ref_type == 'tag'"

      - name: Upload eeprom file
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: builddir/hidrelay.ee.hex
          asset_name: "${{ matrix.name }} eeprom.hex"
        if: "github.event_name == 'push' && github.ref_type == 'tag'"

      - name: Upload fuse config
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: builddir/fuses.txt
          asset_name: "${{ matrix.name }} fuses.txt"
        if: "github.event_name == 'push' && github.ref_type == 'tag'"
