---
name: build
run-name: Build
on:
  pull_request: {}
  push: {}
jobs:
  build:
    name: Build Firmware
    runs-on: Ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: HIDRelayController attiny261
            cross:
              - cross/HIDRelayController_cross.txt
              - cross/attiny261_cross.txt

          - name: HIDRelayController attiny461
            cross:
              - cross/HIDRelayController_cross.txt
              - cross/attiny461_cross.txt

          - name: HIDRelayController attiny861
            cross:
              - cross/HIDRelayController_cross.txt
              - cross/attiny861_cross.txt

          - name: dcttech 8 channel
            cross:
              - cross/dcttech_8ch_cross.txt

          - name: dcttech 2 channel
            cross:
              - cross/dcttech_2ch_cross.txt

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update apt
        run: sudo apt update -y

      - name: Install Dependencies
        run: |
          sudo apt install -y gcc-avr binutils-avr avr-libc avrdude meson clang-format

      - name: Configure ${{ matrix.name }}
        run: |
          meson setup --cross-file=${{ join( matrix.cross, ' --cross-file=') }} builddir

      - name: Check formatting
        run: |
          ninja -C builddir clang-format-check

      - name: Build ${{ matrix.name }}
        run: |
          ninja -C builddir

      - name: Create hex files for ${{ matrix.name }}
        run: |
          ninja -C builddir hidrelay.hex hidrelay.ee.hex

      - name: Create fuse config for ${{ matrix.name }}
        run: |
          ninja -C builddir fuses.txt

      - name: Show stats for ${{ matrix.name }}
        run: |
          ninja -C builddir stats
